services:
  - type: web
    name: backend
    runtime: node
    plan: free
    buildCommand: "cd Backend && npm ci"
    startCommand: "cd Backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
